exclude: |
    (?x)(
        ^jac/jaclang/vendor/|
        ^jac/jaclang/compiler/larkparse/jac_parser\.py$|
        ^$
    )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            pep8-naming,
            # flake8_import_order,
            # flake8_comprehensions,
            # flake8_bugbear,
            # flake8_annotations,
            # flake8_simplify,
          ]
        exclude: |
            (?x)(
                # TODO
                ^jac/examples/|
                /fixtures/|
                ^$
            )
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          - --follow-imports=silent
          - --ignore-missing-imports
          - --config-file=mypy.ini
          - --explicit-package-bases
          - --exclude=jac-byllm/scripts
        additional_dependencies: [types-PyYAML, types-requests]
        exclude: /fixtures/
